name: 'Create Release' 
# 此 workflow 的名稱，功用：創 Release 版本。

on:
  push:
    branches:
      - main

# on：workflow 觸發條件。
# push：當 code 被 push 到 main 分支時，會觸發此 workflow。

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # 現有的 GitHub 官方 Action。將專案程式碼 Checkout，接著可進行測試，部署等。

      - name: Run Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Removed invalid 'plugins' input. Plugin configuration should be moved to a .releaserc file.
  # @semantic-release/commit-analyzer：分析 commit message or PR 標題來決定版本號（major, minor, patch）。
	# @semantic-release/release-notes-generator：生成 Release 說明，可以根據 PR 標題來分類。
	# @semantic-release/changelog：更新 CHANGELOG.md 文件，並將每個 PR 歸類到相應的 Release 說明中。
	# @semantic-release/github：自動在 GitHub 上創一個 Release。
env:
  DEBUG: semantic-release:*
# DEBUG：啟用 semantic-release 的 debug 模式，方便除錯。